name              'daemontools'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides daemontools install, svscan, and service resources'
version           '1.6.19'
source_url        'https://github.com/sous-chefs/daemontools'
issues_url        'https://github.com/sous-chefs/daemontools/issues'
chef_version      '>= 15.3'

depends 'pacman', '~> 1.2'

supports 'amazon', '>= 2023.0'
supports 'arch'
supports 'debian', '>= 12.0'
supports 'gentoo'
supports 'redhat', '>= 9.0'
supports 'ubuntu', '>= 24.04'
