name              'daemontools'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures daemontools'
version           '1.6.19'
source_url        'https://github.com/sous-chefs/daemontools'
issues_url        'https://github.com/sous-chefs/daemontools/issues'

depends 'pacman', '~> 1.2'

suports 'debian'
supports 'ubuntu'
supports 'arch'
supports 'redhat'
supports 'centos'
supports 'gentoo'
supports 'amazon', '>= 2.0'
